### ISSUE TITLE
Error when giving website name

### ISSUE THREAD

**Issue by vikas-wadhwa** [denkGroot/Spina#106]
After running install, the app requests a name: **What would you like to name your website?**

```
== 20160123005505 CreateSpinaTables: migrated (1.9125s) =======================

      create  app/assets/stylesheets/default/application.css.sass
      create  app/views/layouts/default/application.html.haml
      create  app/views/default/shared/_navigation.html.haml
      create  app/views/default/pages/homepage.html.haml
      create  app/views/default/pages/show.html.haml
What would you like to name your website? dgtl-factory.com
/Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security/sanitizer.rb:60:in `process_removed_attributes': Can't mass-assign protected attributes for Spina::Account: name, theme (ActiveModel::MassAssignmentSecurity::Error)
	from /Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security/sanitizer.rb:10:in `sanitize'
	from /Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_model/mass_assignment_security.rb:346:in `sanitize_for_mass_assignment'
	from /Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/attribute_assignment.rb:58:in `assign_attributes'
	from /Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/core.rb:8:in `init_attributes'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/core.rb:196:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/persistence.rb:45:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/spina-0.7.3/lib/generators/spina/install_generator.rb:31:in `create_account'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/generators.rb:157:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/commands/generate.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

This seemed to be a similar issue to #102, but where the error there was

```
attribute_assignment.rb:59:in `rescue in _assign_attribute': unknown attribute 'theme' for Spina::Account. (ActiveRecord::UnknownAttributeError)
```

The issue here is 

```
sanitizer.rb:60:in `process_removed_attributes': Can't mass-assign protected attributes for Spina::Account: name, theme (ActiveModel::MassAssignmentSecurity::Error)
```

**Comment by harmdewit** [comment]
Seems like you're using an older version of rails (< 4.0) or the 'protected_attributes' gem. Spina is currently rails 4+ only. 

Try updating rails, remove protected_attributes or disable `config.active_record.mass_assignment_sanitizer = :strict`.

Seems like a minimum rails version was not yet required by the gemspec, so you didn't get an alert during `bundle install`. Fixing that now.

**Comment by vikas-wadhwa** [comment]
Is there any way to mitigate this while still using protected_attributes? That is a requirement of this project, and I am using rails 4.1.8.

**Comment by harmdewit** [comment]
I believe [this patch](https://github.com/rails/protected_attributes/pull/43) makes that possible to the best extend, you might look into that
