### ISSUE TITLE
I have problem on seed demo data

### ISSUE THREAD

**Issue by nakamuraagatha** [denkGroot/Spina#194]
```
/usr/local/rvm/gems/ruby-2.3.0/gems/spina-0.9.0/lib/generators/spina/install_generator.rb:76:in `seed_demo_content': undefined method `page_parts' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/generators.rb:157:in `invoke'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/generate.rb:13:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from /home/ubuntu/workspace/bin/rails:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by btazi** [comment]
+1

**Comment by a-barbieri** [comment]
The current solution is to setup you `Gemfile` this way.
Soon we'll have Globalize fixed by its team I hope.

    # Gemfile

    gem 'spina-template', '~> 0.4.0'
    gem 'spina', '~>0.10.0'
    # Temporary version (17/09/2016), you might want to check if any working update has been done in the meanwhile
    gem 'globalize', github: 'digitalreflow/globalize', ref: '016ebe8fc2ccc23431f0212c5d3a886199124d4f'

**Comment by nakamuraagatha** [comment]
Great, solve this problem. thanks

and now i have other problem

![spina](https://cloud.githubusercontent.com/assets/5313802/19012130/5aa0fa28-87d6-11e6-8dbc-0ce5e3e49695.jpg)

admin menu broken

**Comment by a-barbieri** [comment]
Have you run `bundle update`?

**Comment by nakamuraagatha** [comment]
yeh, i was bundle update. but steel broken on menu

**Comment by a-barbieri** [comment]
You possibly have something weird going on in your project folder due to updating Spina version.
Try creating a new folder, install Rails 5 from scratch and then add Spina gems as above.
I know Spina versions prior to 0.10.0 have issues with Spina Template 0.4.0 which make views unreliable and updating is always a bit of jump in the dark.

**Comment by Bramjetten** [comment]
Layout issues should be fixed with the latest spina / spina-template merge. Closing this for now.
